// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func Wire() (*Configuration, error) {
	configuration := Provide()
	return configuration, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	Provide,
)
