// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package product

import (
	"database/sql"
	"github.com/google/wire"
	"go-boilerplate/internal/core/domain"
)

// Injectors from wire.go:

func Wire(db *sql.DB) *handler {
	productRepository := ProvideRepository(db)
	productService := ProvideService(productRepository)
	productHandler := ProvideHandler(productService)
	return productHandler
}

// wire.go:

var ProviderSet = wire.NewSet(
	ProvideHandler,
	ProvideService,
	ProvideRepository, wire.Bind(new(domain.ProductHandler), new(*handler)), wire.Bind(new(domain.ProductService), new(*service)), wire.Bind(new(domain.ProductRepository), new(*repository)),
)
